# Development Override f端r Docker Compose
# Optimiert f端r Entwicklung mit Hot-Reload und Debug-Features

services:
  backend:
    environment:
      - DEBUG=True
      - RELOAD=True
      - LANG=de_DE.UTF-8
      - LC_ALL=de_DE.UTF-8
    volumes:
      # Live Code Sync f端r Development
      - ./python-backend:/app:cached
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
      - LANG=de_DE.UTF-8
      - LC_ALL=de_DE.UTF-8
    volumes:
      # Live Code Sync f端r Development
      - ./client:/app:cached
      - /app/node_modules
    command: ["npm", "start"]
    ports:
      - "3002:3000"
    depends_on:
      - backend